Prefix: '&6&lT3SL4Market &8» '
Settings:
  MarketIsmi: '&eMarket Sahibi: &c%player%'
  Fiyat: '&eFiyatı: &7%p TL'
  Adet: '&eMiktarı: &7%p '
  Slot: '&eSlot: &7%slot% '
  EsyaSahibi: '&eEşya Sahibi: &7%player%'
  SadeceOpInfoSatiri: 2
  VergiYuzdesi: 5
  Ortaklik: true
Info:
  - '&5            =&b_&5=&b_&5=&b_&5=&b_&2&lSon&c&lOsmanli&5=&b_&5=&b_&5=&b_&5=&b_'
  - '&e/market kur <Ortaklık-Durum>  &c> &aMarket Oluşturmanı Sağlar.'
  - '&e/market aç <Oyuncu> &c> &aKendi Marketini Ya da Başkasının Marketini Açmanı Sağlar.'
  - '&e/market ekle <Slot> <Fiyat> &c> &aElinde ki Eşyayı Marketine Eklemeni Sağlar.'
  - '&e/market kaldir <Slot> &c> &aBelirlediğin Slotta ki Eşyayı Sana Geri Verir.'
  - '&e/market kaldir hepsi &c> &aMarketinde ki Tüm Eşyaları Kaldırmanı Sağlar.'
  - '&e/market ortaklik &c> &aMarketindeki Ortaklık Sistemini Aktif Eder ya da Kapatır.'
  - '&e/market ortakekle <Oyuncu> &aMarketine Ortak Ekler.'
  - '&e/market ortaksil <Oyuncu> &aMarketindeki Ortağı Kaldırır.'
  - '&e/market ayril &aOrtak Olduğunuz Marketten Ayrılırsınız.'
  - '&e/market ortaklikd <&atrue &e|| &cfalse&e> &aOrtaklık Sistemini Aktif Eder ya da Kapatır.'
  - '&e/market reload &aEklentiyi Yeniler.'
Messages:
  ErrorMessages:
    ZatenMarketVar: '&4Zaten Bir Marketin Var'
    OyuncuBulunamadi: '&4Böyle Bir Oyuncu Bulunamadı'
    ElinizBos: '&4Dostum Markete Eklemek İçin Elinde Bir Şey Olmalı!'
    SlotFazla: "&4Slot Sayısı 53'ten Fazla Olamaz"
    YetersizBakiye: '&4Dostum Bu Eşyayı Almak İçin Yeterince Paran Yok'
    MarketBulunamadi: '&4Marketin Bulunamadı. Lütfen Önce Marketini Kur!'
    SlotZatenDolu: '&4Dostum Bu Slot Dolu Buraya 2 Tane Eşya Ekleyemezsin!'
    Hata: '&4Belirtilmemiş Hata Lütfen Yetkililere Ulaş'
    Console: '&eKonsoldan Bu Komutu Kullanamazsın.'
    PermError: '&4Dostum Maalesef Bunun İçin Yetkin Yok.'
    MarketBulunamadiOrtaklik: '&4Ortaklık İçin Önce Bir Marketin Olmalı.'
    OrtaklikKapali: '&eOrtak Ekleyebilmek İçin Önce Ortaklık Durumunu &atrue &eOlarak Değiştir.'
    Online: '&eEklemek İstediğiniz Oyuncu Çevrimiçi Değil.'
    KendiniOrtakEkleyemezsin: '&eDostum Zaten Marketin Sahibisin.'
    OrtakBulunamadi: '&eBöyle Bir Ortağın Yok.'
    OrtaklikDevredisi: '&eSunucumuzda Ortaklık Sistemi Kapalıdır.'
    ZatenOrtak: '&c%player% &eAdlı Oyuncu Zaten Ortağın.'
    OrtakDegilsin: '&eHerhangi Bir Markete Ortak Değilsin.'
    OrtaklikZatenAktif: '&eOrtaklık Sistemi Zaten &aAktif&e.'
    OrtaklikZatenKapali: '&eOrtaklık Sistemi Zaten &cKapalı&e.'
    ZatenOrtaksin: '&c%player% &eAdlı Oyuncunun Marketine Zaten Ortaksın.'
    EsyayiSenEklemedin: '&eBelirttiğin Slottaki Eşya Sana Ait Değil.'
  SuccessMessages:
    MarketYaratildi: '&aMarketin Başarıyla Oluşturuldu'
    MarketTemizlendi: '&aMarketini Başarıyla Temizledin'
    ItemKaldirildi: '&aSeçtiğin Eşya Marketinden Başarıyla Kaldırıldı!'
    ItemEklendi: '&aSeçtiğin Eşya Başarıyla Marketine Eklendi'
    KendiMarketindenItemAlamazsin: '&4Dostum Kendi Marketinden Eşya Satın Alamazsın'
    ItemAlindi: '&aEşya Başarıyla Satın Alındı!'
    SatinAlmaBasarili: '&aBaşarıyla Satın Aldın!'
    Reload: '&aEklenti Başarıyla Yenilendi'
    OrtaklikAktif: '&eMarketin İçin Ortaklık Sistemi &aAktif Edildi&e.'
    OrtaklikDeAktif: '&eMarketin İçin Ortaklık Sistemin &cKapatıldı&e.'
    OrtakEklendi: '&b%player% &eAdlı Oyuncu Artık Yeni Ortağınız!'
    OrtakOlarakEklendiniz: '&b%player% &eAdlı Oyuncu Sizi Marketine Ortak Olarak Ekledi.'
    OrtakSilindi: '&b%player% &eAdlı Oyuncuyla Artık Ortak Değilsiniz.'
    OrtakliktanCikarildiniz: '&c%player% &eAdlı Oyuncu Sizi Marketinin Ortaklığından Çıkardı.'
    MevcutOrtaklarin: '&eOrtakların: '
    OrtakSiralamasi: '&e%number%# &7-> &a%player%'
    Ayrildiniz: '&c%player% &eAdlı Oyuncunun Marketinden Ayrıldınız.'
    Ayrildi: '&c%player% &eAdlı Oyuncu Marketinizden Ayrıldı.'
    OrtaklikdAktif: '&eOrtaklık Sistemi &aAktif Edilmiştir&e.'
    OrtaklikdPasif: '&eOrtaklık Sistemi &cKapatılmıştır&e.'
    MarketSahibi: '&eMarket Sahibi: '
    MarketSahip: '&4♛ &c%player%'
  UsageMessages:
    EkleKullanim: '&e/market ekle <Slot> <Fiyat>'
    KaldirmaKullanim: '&e/market kaldir <Slot> &c|| &e/market kaldir hepsi'
    KurKullanim: '&e/market kur <Ortaklık> &7> &aOrtaklık Kısmına &atrue &7|| &cfalse &aYaz.'
    OrtaklikdKullanim: '&e/market ortaklikd <&atrue &e|| &cfalse&e>'
    OrtaklikKullanim: '&e/market ortaklik <&atrue &e|| &cfalse&e>'
    OrtakekleKullanim: '&e/market ortakekle <Oyuncu>'
    OrtaksilKullanim: '&e/market ortaksil <Oyuncu>'
    OrtaklarKullanim: '&e/market ortaklar'
    AyrilKullanim: '&e/market ayril'
    ReloadKullanim: '&e/market reload'